spring:
  application:
    name: feature-toggle-read
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5434/feature_toggle_read
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feature-toggle-read

topics:
  feature-toggle-events: feature-toggle-events
  feature-toggle-configuration-events: feature-toggle-configuration-events

server:
  port: 8083